name: 🚀 Deploy automático para FTP (k7-app)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ftp-deploy-k7-app
  cancel-in-progress: true

jobs:
  ftp-deploy:
    name: Enviar para servidor FTP (k7-app)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 191.252.196.127
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21

          # >>> Ajuste o destino aqui (diretório inicial do seu usuário FTP + este caminho)
          server-dir: /k7-app/

          # Mantém cache de estado no servidor para enviar só o que mudou
          state-name: .ftp-deploy-sync-state-k7-app.json

          # Excluir coisas inúteis/sensíveis
          exclude: |
            **/.git/**
            **/.github/**
            **/.gitignore
            **/.gitmodules
            **/.DS_Store
            **/*.map
            **/*.lock
            **/*.log
            **/node_modules/**
            **/node/.wwebjs_auth/**
            **/node/.wwebjs_cache/**
            **/public/uploads/**
            **/public/plugins/**
            **/.env
            **/deploy.yml

          # dica: use isto UMA VEZ se precisar “zerar” a pasta remota
          # dangerous-clean-slate: true
